@extends('layouts.app', ['title' => 'Academic Period & Sanction Policy'])
@section('content')
<section class="page-heading"><div><p class="eyebrow">SPMU Head configuration</p><h1>Academic Periods & Sanction Rules</h1><p>Historical sanctions keep the rule applied at the time. Changing configuration does not rewrite old records.</p></div></section>
<section class="content-grid two">
<article class="card"><div class="card-header"><div><p class="eyebrow">Academic calendar</p><h2>Add / activate period</h2></div></div><form method="post" action="{{ route('policies.academic-periods.store') }}" class="form-grid">@csrf<div class="form-columns"><label>Academic Year<input name="academic_year" placeholder="2026-2027" required></label><label>Term<select name="term_code" required><option value="FIRST_SEMESTER">1st Semester</option><option value="SECOND_SEMESTER">2nd Semester</option><option value="SUMMER_MIDYEAR">Summer / Midyear</option></select></label><label>Term Name<input name="term_name" required></label><label>Start Date<input type="date" name="start_date" required></label><label>End Date<input type="date" name="end_date" required></label><label>Status<select name="status"><option>UPCOMING</option><option>ACTIVE</option><option>COMPLETED</option></select></label></div><button class="button primary">Save Academic Period</button></form></article>
<article class="card"><div class="card-header"><div><p class="eyebrow">Sanction recommendation</p><h2>Add configurable rule</h2></div></div><form method="post" action="{{ route('policies.sanction-rules.store') }}" class="form-grid">@csrf<div class="form-columns"><label>Offense No.<input type="number" min="1" name="offense_no" required></label><label>Sanction Code<input name="sanction_code" placeholder="NOTICE / WRITTEN_REPRIMAND / SUSPENSION" required></label><label>Label<input name="sanction_label" required></label><label>Duration<select name="duration_mode"><option value="NONE">None</option><option value="END_OF_PERIOD">Remainder of current period</option><option value="MANUAL">Manual</option></select></label><label>Status<select name="status"><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option></select></label><label>Effective From<input type="date" name="effective_from"></label><label>Effective To<input type="date" name="effective_to"></label></div><button class="button primary">Save Sanction Rule</button></form></article>
</section>
<section class="content-area"><article class="card"><div class="card-header"><div><p class="eyebrow">Periods</p><h2>Configured Academic Periods</h2></div></div><div class="table-wrap"><table><thead><tr><th>AY</th><th>Term</th><th>Dates</th><th>Status</th></tr></thead><tbody>@forelse($academicPeriods as $period)<tr><td>{{ $period->academic_year }}</td><td>{{ $period->term_name }}</td><td>{{ $period->start_date->format('d M Y') }} – {{ $period->end_date->format('d M Y') }}</td><td><x-status-badge :status="$period->status" /></td></tr>@empty<tr><td colspan="4">No periods configured.</td></tr>@endforelse</tbody></table></div></article></section>
<section class="content-area"><article class="card"><div class="card-header"><div><p class="eyebrow">Rules</p><h2>Configured Sanction Rules</h2></div></div><div class="table-wrap"><table><thead><tr><th>Offense</th><th>Code</th><th>Label</th><th>Duration</th><th>Status</th></tr></thead><tbody>@forelse($sanctionRules as $rule)<tr><td>{{ $rule->offense_no }}</td><td>{{ $rule->sanction_code }}</td><td>{{ $rule->sanction_label }}</td><td>{{ str($rule->duration_mode)->replace('_',' ')->title() }}</td><td><x-status-badge :status="$rule->status" /></td></tr>@empty<tr><td colspan="5">No sanction rules configured.</td></tr>@endforelse</tbody></table></div></article></section>
@endsection
