@extends('layouts.app', ['title' => $custody->custody_no])
@section('content')
@php
    $workspace=session('active_workspace');
    $isBorrower=$workspace==='BORROWER' && auth()->id()===$custody->borrower_user_id;
    $isOfficer=$workspace==='SPMU' && auth()->user()->access_classification?->value==='SPMU_OFFICER';
    $isHead=$workspace==='SPMU' && (auth()->user()->access_classification?->value==='SPMU_HEAD' || auth()->user()->activeDelegationFor('SPMU'));
    $hasLinen=$custody->lines->contains(fn($line)=>(bool)$line->requestItem->inventoryItem->laundry_required);
@endphp
<section class="page-heading"><div><p class="eyebrow">{{ $custody->custody_no }}</p><h1>Borrower’s Slip and item custody</h1><p><span class="status">{{ str_replace('_',' ',$custody->status) }}</span> · Return deadline {{ $custody->due_at->format('F j, Y g:i A') }}</p></div><a class="button secondary" href="{{ route('custody.index') }}">Back to borrowings</a></section>

<section class="content-grid"><article class="card"><p class="eyebrow">Read-only approved record</p><h2>Custody details</h2><dl class="detail-list"><dt>Borrower</dt><dd>{{ $custody->borrower->full_name }}</dd><dt>Request</dt><dd><a href="{{ route('requests.show',$custody->request) }}">{{ $custody->request->request_no }}</a></dd><dt>Purpose</dt><dd>{{ $custody->request->currentVersion->purpose_event }}</dd><dt>Release schedule</dt><dd>{{ optional($custody->scheduled_release_at)->format('F j, Y g:i A') ?: 'To be scheduled' }}</dd><dt>Actual release</dt><dd>{{ optional($custody->released_at)->format('F j, Y g:i A') ?: 'Not physically released' }}</dd></dl></article><article class="card"><p class="eyebrow">Controlled outputs</p><h2>Official documents</h2><div class="document-list">@forelse($documents->whereNotIn('status',['INVALIDATED','EXPIRED','SUPERSEDED']) as $document)<article><div><strong>{{ str_replace('_',' ',$document->document_type) }}</strong><small>{{ $document->document_no }} · {{ $document->status }}</small></div><a class="button secondary small" href="{{ route('documents.download',$document) }}">Download</a></article>@empty<p class="empty-state">Documents appear as each required step is completed.</p>@endforelse</div></article></section>

<section class="content-area"><article class="card"><div class="card-header"><div><p class="eyebrow">Item-level monitoring</p><h2>Issued and return status</h2></div></div><div class="table-wrap"><table><thead><tr><th>Item</th><th>Location</th><th>Approved / final issued</th><th>Released / returned</th><th>Item status</th><th>Compliance</th></tr></thead><tbody>@foreach($custody->lines as $line)<tr><td><strong>{{ $line->requestItem->description_snapshot }}</strong><small>{{ $line->requestItem->inventoryItem->item_type }}</small></td><td>{{ str_replace('_',' ',$line->requestItem->use_location) }}</td><td>{{ $line->approved_quantity+0 }} / {{ $line->quantity_to_receive+0 }} {{ $line->requestItem->unit_snapshot }}</td><td>{{ $line->actual_released_quantity+0 }} / {{ $line->returned_quantity+0 }}</td><td><span class="status">{{ str_replace('_',' ',$line->item_status) }}</span></td><td>{{ str_replace('_',' ',$line->compliance_status) }}</td></tr>@endforeach</tbody></table></div></article></section>

@if($isOfficer && $custody->status==='PREPARING_RELEASE' && !$custody->acknowledged_at)
<section class="content-grid"><form method="post" action="{{ route('custody.quantities',$custody) }}" class="card form-grid">@csrf<p class="eyebrow">SPMU Action Officer</p><h2>Record final issued quantities</h2><p>Only SPMU may reduce the approved quantities after the final physical count. No item may be increased or substituted.</p>@foreach($custody->lines as $line)<div class="form-columns"><label>{{ $line->requestItem->description_snapshot }}<input type="number" step="0.001" min="0" max="{{ $line->approved_quantity }}" name="quantities[{{ $line->id }}]" value="{{ $line->quantity_to_receive }}"></label><label>Reason if reduced<input name="reasons[{{ $line->id }}]" value="{{ $line->adjustment_reason }}"></label></div>@endforeach<button class="button primary">Save final quantities</button></form><form method="post" action="{{ route('custody.prepare',$custody) }}" class="card">@csrf<p class="eyebrow">Physical preparation</p><h2>Verify prepared items</h2><p>Count and inspect every item, then confirm the displayed final issued quantities. This unlocks the borrower's digital acknowledgement.</p><button class="button primary">Verify preparation</button></form></section>
@endif

@if($isBorrower && $custody->status==='PREPARING_RELEASE' && !$custody->acknowledged_at)
<section class="content-area narrow"><form method="post" action="{{ route('custody.acknowledge',$custody) }}" class="card">@csrf<p class="eyebrow">Borrower digital signature</p><h2>Acknowledge the Borrower’s Slip</h2><p>SPMU preparation: <strong>{{ $custody->prepared_at ? 'Completed' : 'Pending' }}</strong>. Your current profile e-signature will be bound to this read-only acknowledgement{{ $hasLinen ? ' and to the Laundry Form' : '' }}.</p><button class="button primary" @disabled(!$custody->prepared_at)>E-sign acknowledgement</button></form></section>
@endif

@if($custody->gatePass && $custody->status==='PREPARING_RELEASE')
<section class="content-grid"><article class="card"><p class="eyebrow">Conditional Gate Pass</p><h2>Digital approval before printing</h2><dl class="detail-list"><dt>Verified by</dt><dd>{{ $custody->gatePass->preparedVerifier?->full_name ?: 'Pending SPMU Action Officer' }}<small>{{ optional($custody->gatePass->prepared_verified_at)->format('F j, Y g:i A') }}</small></dd><dt>Approved by</dt><dd>{{ $custody->gatePass->approver?->full_name ?: 'Pending SPMU Head' }}<small>{{ optional($custody->gatePass->approved_at)->format('F j, Y g:i A') }}</small></dd><dt>Guard</dt><dd>Wet signature after campus exit</dd></dl></article><div class="card"><p class="eyebrow">Authorized action</p><h2>Gate Pass signatures</h2>@if($isOfficer && !$custody->gatePass->prepared_verified_at)<form method="post" action="{{ route('gate-passes.sign-verified',$custody->gatePass) }}">@csrf<button class="button primary">E-sign “Verified By”</button></form>@elseif($isHead && $custody->gatePass->prepared_verified_at && !$custody->gatePass->approved_at)<form method="post" action="{{ route('gate-passes.sign-approved',$custody->gatePass) }}">@csrf<button class="button primary">E-sign “Approved By”</button></form>@else<p class="empty-state">The next signature belongs to a different authorized SPMU user.</p>@endif</div></section>
@endif

@if($hasLinen && $custody->status==='PREPARING_RELEASE')
<section class="content-area narrow"><article class="card"><p class="eyebrow">Conditional Laundry Form</p><h2>Borrower + SPMU Head digital approval</h2><p>Borrower signature: <strong>{{ $custody->laundry_borrower_signature_snapshot_id ? 'Completed' : 'Pending' }}</strong><br>SPMU Head approval: <strong>{{ $custody->laundry_approved_at ? 'Completed' : 'Pending' }}</strong><br>Laundry worker: <strong>Wet signature during service</strong></p>@if($isHead && $custody->laundry_borrower_signature_snapshot_id && !$custody->laundry_approved_at)<form method="post" action="{{ route('laundry.approve-form',$custody) }}">@csrf<button class="button primary">E-sign Laundry Form approval</button></form>@endif</article></section>
@endif

@if($isOfficer && $custody->status==='PREPARING_RELEASE')
<section class="content-area narrow"><form method="post" action="{{ route('custody.release',$custody) }}" class="card">@csrf<p class="eyebrow">SPMU release desk</p><h2>Complete physical release</h2><p>This changes only the final issued quantities from Allocated to Borrowed. Any unused allocation is restored immediately.</p><button class="button primary">Release counted items</button></form></section>
@endif

@foreach($documents->whereIn('document_type',['GATE_PASS','LAUNDRY_FORM'])->where('status','FINAL') as $document)
<section class="content-grid"><form method="post" action="{{ route('evidence.store',$document) }}" enctype="multipart/form-data" class="card form-grid">@csrf<p class="eyebrow">Paper signature evidence</p><h2>{{ str_replace('_',' ',$document->document_type) }} upload</h2><p>The borrower normally uploads the signed scan. SPMU fallback is allowed only with an attributable reason.</p><label>Signed scanned copy<input type="file" name="evidence" accept="application/pdf,image/png,image/jpeg,image/webp" required></label>@if($workspace==='SPMU')<label>SPMU fallback reason<textarea name="fallback_reason"></textarea></label>@endif<button class="button primary">Upload for verification</button></form><article class="card"><p class="eyebrow">Evidence history</p><h2>Submitted copies</h2>@forelse($document->evidence as $evidence)<div class="evidence-row"><div><strong>{{ $evidence->verification_status }}</strong><small>{{ $evidence->upload_mode }} · {{ $evidence->submitted_at->format('M j, Y g:i A') }}</small><a href="{{ route('files.show',$evidence->stored_file_id) }}" target="_blank">View evidence</a></div>@if($isOfficer && $evidence->verification_status==='PENDING_VERIFICATION')<form method="post" action="{{ route('evidence.verify',$evidence) }}" class="inline-actions">@csrf<input name="reason" placeholder="Reason if rejected"><button name="decision" value="VERIFIED">Verify</button><button name="decision" value="REJECTED">Reject</button></form>@endif</div>@empty<p class="empty-state">No evidence uploaded.</p>@endforelse</article></section>
@endforeach

@if($isBorrower && in_array($custody->status,['ACTIVE','PARTIALLY_RETURNED','OVERDUE'],true))
<section class="content-area"><form method="post" action="{{ route('custody.early-return',$custody) }}" class="card form-grid">@csrf<p class="eyebrow">Borrower-initiated notice</p><h2>Request an Early Return</h2><p>This schedules a physical handover; it does not change inventory until SPMU receives and inspects the items.</p><label>Proposed handover date and time<input type="datetime-local" name="proposed_return_at" required></label><div class="table-wrap"><table><thead><tr><th>Item</th><th>Outstanding</th><th>Quantity to return early</th></tr></thead><tbody>@foreach($custody->lines as $line)@php($outstanding=max(0,(float)$line->actual_released_quantity-(float)$line->returned_quantity))<tr><td>{{ $line->requestItem->description_snapshot }}</td><td>{{ $outstanding }}</td><td><input type="number" step="0.001" min="0" max="{{ $outstanding }}" name="quantities[{{ $line->id }}]" value="0"></td></tr>@endforeach</tbody></table></div><label>Reason or coordination note<textarea name="reason"></textarea></label><button class="button primary">Send Early Return notice</button></form></section>
@endif

@if($isOfficer && $custody->gatePass && $custody->gatePass->approved_at && $custody->gatePass->status!=='VERIFIED')
<section class="content-area narrow"><form method="post" action="{{ route('gate-passes.verify',$custody->gatePass) }}" class="card form-grid">@csrf<p class="eyebrow">After campus exit</p><h2>Verify the guard-signed Gate Pass</h2><p>First verify the uploaded scan against the original. Then record the guard's wet-signature details.</p><div class="form-columns"><label>Guard on duty<input name="guard_name" required></label><label>Guard signed date and time<input type="datetime-local" name="guard_signed_at" required></label></div><button class="button primary">Complete Gate Pass verification</button></form></section>
@endif

@foreach($custody->returns->flatMap->lines->filter->laundryRecord as $laundry)
@if($isOfficer && $laundry->status!=='VERIFIED')<section class="content-area narrow"><form method="post" action="{{ route('laundry.verify',$laundry) }}" class="card form-grid">@csrf<p class="eyebrow">After laundry service</p><h2>Verify worker signature and linen condition</h2><p>Verify the uploaded form against the original, then record the worker's wet signature and the final physical inspection.</p><div class="form-columns"><label>Laundry worker<input name="worker_name" required></label><label>Received at<input type="datetime-local" name="worker_received_at" required></label><label>Completed at<input type="datetime-local" name="worker_completed_at" required></label><label>Cleaned quantity<input type="number" step="0.001" min="0" name="cleaned_quantity" value="{{ $laundry->returnLine->quantity_received }}" required></label><label>Damaged quantity<input type="number" step="0.001" min="0" name="damaged_quantity" value="0" required></label></div><button class="button primary">Verify laundry completion</button></form></section>@endif
@endforeach

@if($isOfficer && in_array($custody->status,['ACTIVE','PARTIALLY_RETURNED','OVERDUE','EARLY_RETURN','INCIDENT_OPEN'],true))
<section class="content-area"><form method="post" action="{{ route('custody.return',$custody) }}" enctype="multipart/form-data" class="card form-grid">@csrf<p class="eyebrow">SPMU physical inspection</p><h2>Receive returned items</h2><label class="checkbox"><input type="checkbox" name="early_return" value="1"> Match an active Early Return notice</label><div class="table-wrap"><table><thead><tr><th>Item</th><th>Outstanding</th><th>Quantity now</th><th>Condition</th><th>Incident evidence</th></tr></thead><tbody>@foreach($custody->lines as $line)@php($outstanding=max(0,(float)$line->actual_released_quantity-(float)$line->returned_quantity))<tr><td>{{ $line->requestItem->description_snapshot }}</td><td>{{ $outstanding }}</td><td><input type="number" step="0.001" min="0" max="{{ $outstanding }}" name="quantities[{{ $line->id }}]" value="0"></td><td><select name="conditions[{{ $line->id }}]"><option>FINE</option><option>DAMAGED</option><option>DESTROYED</option><option>MISSING</option><option>LOST</option><option>STOLEN</option></select></td><td><input name="police_blotter_references[{{ $line->id }}]" placeholder="Blotter ref. if stolen"><input type="file" name="evidence_files[{{ $line->id }}]" accept="application/pdf,image/png,image/jpeg,image/webp"></td></tr>@endforeach</tbody></table></div><label>Inspection remarks<textarea name="remarks"></textarea></label><button class="button primary">Record physical return</button></form></section>
@endif
@endsection
