@extends('layouts.app', ['title' => 'Accountability'])
@section('content')
@php($workspace=session('active_workspace'))
<section class="page-heading"><div><p class="eyebrow">Penalties and property charges only</p><h1>Accountability records</h1><p>The borrower uploads a receipt copy. SPMU inspects the original, encodes the Official Receipt details, and verifies or rejects the submission.</p></div></section>

<section class="content-area"><div class="card-header"><div><p class="eyebrow">Deadline compliance</p><h2>Overdue cases</h2></div></div><div class="card-grid">@forelse($overdueCases as $overdue)<article class="card"><span class="status">{{ $overdue->status }}</span><h3>{{ $overdue->custody->custody_no }} · Offense {{ $overdue->offense_level }}</h3><p>{{ $overdue->borrower->full_name }} · {{ str_replace('_',' ',$overdue->sanction_type) }}</p><p>Grace expired {{ $overdue->grace_expires_at->format('M j, Y g:i A') }}. Rate: {{ $overdue->rate_snapshot === null ? 'Pending configuration' : 'PHP '.number_format((float)$overdue->rate_snapshot,2).'/day' }}. Accrued: <strong>PHP {{ number_format((float)$overdue->accrued_amount,2) }}</strong>.</p>@if($workspace==='SPMU' && $overdue->status==='RETURNED_PENDING_SETTLEMENT' && !$overdue->penalties->where('status','!=','VOID')->count())<form method="post" action="{{ route('overdue.bill',$overdue) }}" class="form-grid top-gap">@csrf<label>Assessment basis<textarea name="basis" required>Configured daily tariff × recorded overdue days after the 24-hour grace period.</textarea></label><label>Due date<input type="date" name="due_at"></label><button class="button primary">Generate penalty Billing Statement</button></form>@endif</article>@empty<div class="empty-state">No overdue cases recorded.</div>@endforelse</div></section>

<section class="content-area"><div class="card-header"><div><p class="eyebrow">Property responsibility</p><h2>Incidents</h2></div></div><div class="card-grid">@forelse($incidents as $incident)<article class="card"><span class="status">{{ $incident->status }}</span><h3>{{ $incident->incident_no }} · {{ $incident->incident_type }}</h3><p>{{ $incident->borrower->full_name }}</p><p>{{ $incident->remarks }}</p>@if($incident->police_blotter_reference)<p>Police blotter: <strong>{{ $incident->police_blotter_reference }}</strong></p>@endif @if($incident->supporting_evidence_file_id)<a href="{{ route('files.show',$incident->supporting_evidence_file_id) }}" target="_blank">View incident evidence</a>@endif<small>Reported {{ $incident->reported_at->format('M j, Y g:i A') }}</small>@if($workspace==='SPMU' && $incident->status==='OPEN')<form method="post" action="{{ route('incidents.bill',$incident) }}" class="form-grid top-gap">@csrf<label>Authorized property-charge amount<input type="number" step="0.01" min="0.01" name="amount" required></label><label>Assessment basis<textarea name="basis" required></textarea></label><label>Due date<input type="date" name="due_at"></label><button class="button primary">Generate property-charge Billing Statement</button></form>@endif</article>@empty<div class="empty-state">No incidents recorded.</div>@endforelse</div></section>

<section class="content-area"><div class="card-header"><div><p class="eyebrow">External payment evidence</p><h2>Billing Statements</h2></div></div><div class="card-grid">@forelse($billings as $billing)<article class="card"><span class="status">{{ $billing->status }}</span><h3>{{ $billing->billing_no }}</h3><p>{{ $billing->borrower->full_name }} · <strong>PHP {{ number_format((float)$billing->total_amount,2) }}</strong></p>@foreach($billing->lines as $line)<p>{{ str_replace('_',' ',$line->line_type) }}: {{ $line->description }}</p>@endforeach @foreach($billing->documents as $document)<a class="button secondary small" href="{{ route('documents.download',$document) }}">Download Billing Statement</a>@endforeach
@if($workspace==='BORROWER' && !in_array($billing->status,['SETTLED','WAIVED','VOID'],true))<form method="post" action="{{ route('payments.store',$billing) }}" enctype="multipart/form-data" class="form-grid top-gap">@csrf<h4>Upload receipt copy</h4><p>Do not encode the OR number or amount here. SPMU records those fields after checking the original receipt.</p><label>Receipt image or PDF<input type="file" name="evidence" accept="application/pdf,image/png,image/jpeg,image/webp" required></label><label>Note to SPMU<textarea name="remarks"></textarea></label><button class="button secondary">Submit receipt copy</button></form>@endif
@foreach($billing->payments as $payment)<div class="evidence-row"><div><strong>{{ $payment->official_receipt_no ? 'OR '.$payment->official_receipt_no : 'Receipt copy submitted' }}</strong><small>{{ str_replace('_',' ',$payment->status) }}{{ $payment->amount ? ' · PHP '.number_format((float)$payment->amount,2) : '' }}</small>@if($payment->evidence_file_id)<a href="{{ route('files.show',$payment->evidence_file_id) }}" target="_blank">View receipt copy</a>@endif</div>@if($workspace==='SPMU' && $payment->status==='SUBMITTED_PENDING_ORIGINAL')<form method="post" action="{{ route('payments.verify',$payment) }}" class="form-grid">@csrf<div class="form-columns"><label>OR number<input name="official_receipt_no"></label><label>Receipt date<input type="date" name="receipt_date"></label><label>Verified amount<input type="number" step="0.01" min="0.01" name="amount"></label><label>Inspection remarks<input name="remarks" required></label></div><div class="inline-actions"><button name="decision" value="VERIFIED">Verify original and encode</button><button name="decision" value="REJECTED">Reject</button></div></form>@endif</div>@endforeach
@if($workspace==='SPMU' && !in_array($billing->status,['SETTLED','WAIVED','VOID'],true))<form method="post" action="{{ route('billings.waive',$billing) }}" class="form-grid top-gap danger-zone">@csrf<label>Authorized waiver reason<textarea name="reason" required></textarea></label><button class="button danger small">Record authorized waiver</button></form>@endif</article>@empty<div class="empty-state">No billing statements.</div>@endforelse</div></section>

<section class="content-area"><article class="card"><p class="eyebrow">Borrowing eligibility</p><h2>Restrictions</h2><div class="table-wrap"><table><thead><tr><th>Type</th><th>Reason</th><th>Effective</th><th>Status</th></tr></thead><tbody>@forelse($restrictions as $restriction)<tr><td>{{ str_replace('_',' ',$restriction->restriction_type) }}</td><td>{{ $restriction->reason }}</td><td>{{ $restriction->effective_from->format('M j, Y') }}{{ $restriction->effective_to ? ' to '.$restriction->effective_to->format('M j, Y') : '' }}</td><td><span class="status">{{ $restriction->status }}</span></td></tr>@empty<tr><td colspan="4" class="empty-state">No borrowing restrictions.</td></tr>@endforelse</tbody></table></div></article></section>
@endsection
