@extends('layouts.app', ['title' => 'Reports and Analytics'])
@section('content')
<section class="page-heading">
    <div><p class="eyebrow">Descriptive analytics and KPI evidence</p><h1>Reports and performance monitoring</h1></div>
    <div class="actions">@if(auth()->user()->hasRole('SPMU') || auth()->user()->hasRole('ICTU'))<a class="button secondary" href="{{ route('reports.audit') }}">Audit trail</a><a class="button secondary" href="{{ route('reports.notifications') }}">Notification delivery</a>@endif<button class="button primary" onclick="window.print()">Print report</button></div>
</section>
<section class="content-area">
    <form method="get" class="card form-columns"><label>Period from<input type="date" name="from" value="{{ $from->toDateString() }}"></label><label>Period to<input type="date" name="to" value="{{ $to->toDateString() }}"></label><button class="button primary">Apply period</button></form>
    <div class="actions top-gap">@foreach(['inventory','borrowing','utilization','overdue','penalty','compliance'] as $type)<a class="button secondary small" href="{{ route('reports.export',['type'=>$type,'from'=>$from->toDateString(),'to'=>$to->toDateString()]) }}">Export {{ ucfirst($type) }} CSV</a>@endforeach @if(auth()->user()->hasRole('SPMU') || auth()->user()->hasRole('ICTU')) @foreach(['notification','audit'] as $type)<a class="button secondary small" href="{{ route('reports.export',['type'=>$type,'from'=>$from->toDateString(),'to'=>$to->toDateString()]) }}">Export {{ ucfirst($type) }} CSV</a>@endforeach @endif</div>
</section>
<section class="content-grid three"><div class="card"><span class="eyebrow">Audit evidence</span><strong class="metric">{{ number_format($auditCount) }}</strong><p>Attributable business and technical events</p></div><div class="card"><span class="eyebrow">Failed deliveries</span><strong class="metric">{{ number_format($failedNotifications) }}</strong><p>Visible provider/configuration failures</p></div><div class="card"><span class="eyebrow">Tracked inventory</span><strong class="metric">{{ number_format($items->count()) }}</strong><p>Quantity-based descriptions</p></div></section>
<section class="content-grid three"><div class="card"><span class="eyebrow">Overdue / repeat</span><strong class="metric">{{ $overdueCount }} / {{ $repeatOffenders }}</strong><p>Overdue cases and repeat borrowers in period</p></div><div class="card"><span class="eyebrow">Penalty value</span><strong class="metric">PHP {{ number_format((float)$penaltyTotal,2) }}</strong><p>Assessed penalties in period</p></div><div class="card"><span class="eyebrow">Return compliance</span><strong class="metric">{{ number_format($returnCompliance['percentage'],1) }}%</strong><p>{{ $returnCompliance['closed'] }} closed of {{ $returnCompliance['released'] }} released · {{ $dueSoonCount }} due soon</p></div></section>
<section class="content-grid two"><div class="card"><h2>Request status distribution</h2><div class="bar-list">@forelse($requestStatuses as $status=>$total)<div><span>{{ str_replace('_',' ',$status) }}</span><strong>{{ $total }}</strong></div>@empty<p>No request data.</p>@endforelse</div></div><div class="card"><h2>Custody status distribution</h2><div class="bar-list">@forelse($custodyStatuses as $status=>$total)<div><span>{{ str_replace('_',' ',$status) }}</span><strong>{{ $total }}</strong></div>@empty<p>No custody data.</p>@endforelse</div></div></section>
<section class="content-area"><div class="card"><h2>Inventory state report</h2><div class="table-wrap"><table><thead><tr><th>Item</th><th>Category</th><th>Total</th><th>Available</th><th>Allocated</th><th>Borrowed</th><th>Laundry</th><th>Damaged / Maintenance</th><th>Lost</th><th>Stolen</th><th>Destroyed</th><th>Condemned</th></tr></thead><tbody>@foreach($items as $item)<tr><td>{{ $item->unique_description }}</td><td>{{ $item->category->category_name }}</td><td>{{ $balances[$item->id]['total'] }}</td><td>{{ $balances[$item->id]['available'] }}</td><td>{{ $balances[$item->id]['allocated'] }}</td><td>{{ $balances[$item->id]['borrowed'] }}</td><td>{{ $balances[$item->id]['laundry'] }}</td><td>{{ $balances[$item->id]['damaged_maintenance'] }}</td><td>{{ $balances[$item->id]['lost'] }}</td><td>{{ $balances[$item->id]['stolen'] }}</td><td>{{ $balances[$item->id]['destroyed'] }}</td><td>{{ $balances[$item->id]['condemned'] }}</td></tr>@endforeach</tbody></table></div></div></section>
<section class="content-area"><div class="card"><h2>Utilization ranking</h2><div class="bar-list">@foreach($topItems as $item)<div><span>{{ $item->unique_description }}</span><strong>{{ $item->used_quantity+0 }} released</strong></div>@endforeach</div><div class="callout"><strong>Manuscript KPI formulas</strong><p>Average recorded digital approval cycle: {{ $averageApprovalSeconds ? gmdate('H:i:s',$averageApprovalSeconds) : 'No completed cycle in period' }}. Time Efficiency = ((Old Processing Time - New Processing Time) / Old Processing Time) × 100 · Accuracy = Correct Transactions / Total Transactions × 100 · Productivity = Total Output / Total Input.</p></div></div></section>
@endsection
