@extends('layouts.app', ['title' => $borrowingRequest->exists ? 'Edit Request' : 'Create Request'])
@section('content')
@php($selected = $version->exists ? $version->items->keyBy('inventory_item_id') : collect())
<section class="page-heading"><div><p class="eyebrow">Official borrowing request</p><h1>{{ $borrowingRequest->exists ? 'Edit request draft' : 'Create a borrowing request' }}</h1><p>Choose the complete use period first. Availability and quantity limits apply across that full period.</p></div><div class="step-chip">Step 1 of 2 · Draft</div></section>
<section class="content-area"><form method="post" action="{{ $borrowingRequest->exists ? route('requests.update', $borrowingRequest) : route('requests.store') }}" class="form-grid" id="request-form">@csrf @if($borrowingRequest->exists)@method('PUT')@endif
    <div class="card form-section"><div class="section-number">01</div><div><h2>Event and accountable use</h2><p class="meta">Dates cannot be extended after approval.</p></div><div class="form-columns full-span"><label>Purpose/Event<input name="purpose_event" value="{{ old('purpose_event', $version->purpose_event) }}" required></label><label>General event location<input name="location" value="{{ old('location', $version->location) }}" required></label><label>Needed from<input id="needed_from" type="datetime-local" name="needed_from" value="{{ old('needed_from', optional($version->needed_from)->format('Y-m-d\TH:i')) }}" required></label><label>Return deadline<input id="return_due_at" type="datetime-local" name="return_due_at" value="{{ old('return_due_at', optional($version->return_due_at)->format('Y-m-d\TH:i')) }}" required></label></div><label class="full-span">Event details<textarea name="event_details" required>{{ old('event_details', $version->event_details) }}</textarea></label><label class="full-span">Remarks<textarea name="remarks">{{ old('remarks', $version->remarks) }}</textarea></label></div>
    <div class="card form-section"><div class="section-number">02</div><div><h2>Represented student activity</h2><p class="meta">The employee remains the accountable borrower.</p></div><label class="checkbox full-span"><input id="represents_students" type="checkbox" name="represents_student_activity" value="1" @checked(old('represents_student_activity', $version->represents_student_activity))> This request represents a student activity</label><div id="student-fields" class="form-columns full-span"><label>Student organization <small>if applicable</small><input name="student_organization" value="{{ old('student_organization', $version->student_organization) }}"></label><label>Program/Department<input name="represented_program_department" value="{{ old('represented_program_department', $version->represented_program_department) }}"></label><label>Year level<input name="represented_year_level" value="{{ old('represented_year_level', $version->represented_year_level) }}"></label></div></div>
    <div class="card form-section"><div class="section-number">03</div><div><h2>Requested inventory</h2><p class="meta" id="availability-message">Choose valid dates to calculate real-time availability.</p></div><div class="table-wrap full-span"><table><thead><tr><th>Select</th><th>Property description</th><th>Unit</th><th>Available for period</th><th>Quantity</th><th>Use location</th></tr></thead><tbody>@foreach($items as $item)@php($requestItem=$selected->get($item->id))<tr><td><input type="checkbox" name="item_ids[]" value="{{ $item->id }}" @checked(old("quantities.$item->id", $requestItem?->requested_quantity ?? 0)>0)></td><td><strong>{{ $item->unique_description }}</strong><small>{{ $item->specification }}</small>@if($item->laundry_required)<span class="badge">Linen · Laundry Form</span>@endif @if($item->off_campus_allowed)<span class="badge">Barricade · Gate Pass eligible</span>@endif</td><td>{{ $item->unit->unit_name }}</td><td><strong class="availability-value" data-item="{{ $item->id }}">Select dates</strong><small>Total stock: {{ $item->total_quantity+0 }}</small></td><td><input class="quantity-input" type="number" step="0.001" min="0" max="{{ $item->total_quantity }}" name="quantities[{{ $item->id }}]" value="{{ old("quantities.$item->id", $requestItem?->requested_quantity ?? 0) }}"></td><td>@if($item->off_campus_allowed)<select name="locations[{{ $item->id }}]"><option value="ON_CAMPUS" @selected(old("locations.$item->id",$requestItem?->use_location)==='ON_CAMPUS')>On-Campus</option><option value="OFF_CAMPUS" @selected(old("locations.$item->id",$requestItem?->use_location)==='OFF_CAMPUS')>Off-Campus</option></select>@else<input type="hidden" name="locations[{{ $item->id }}]" value="ON_CAMPUS"><span class="locked-value">On-Campus · Locked</span>@endif</td></tr>@endforeach</tbody></table></div></div>
    <div class="actions sticky-actions"><button class="button primary">Save and generate official preview</button><a class="button secondary" href="{{ route('requests.index') }}">Cancel editing</a></div>
</form></section>
<script>
const studentToggle=document.getElementById('represents_students'); const studentFields=document.getElementById('student-fields');
function toggleStudentFields(){studentFields.classList.toggle('is-hidden',!studentToggle.checked); studentFields.querySelectorAll('input').forEach((el)=>{if(el.name!=='student_organization')el.required=studentToggle.checked;});}
studentToggle.addEventListener('change',toggleStudentFields); toggleStudentFields();
let availabilityTimer;
async function refreshAvailability(){const from=document.getElementById('needed_from').value;const to=document.getElementById('return_due_at').value;if(!from||!to)return;clearTimeout(availabilityTimer);availabilityTimer=setTimeout(async()=>{const message=document.getElementById('availability-message');message.textContent='Checking real-time availability…';try{const response=await fetch(`{{ route('inventory.availability') }}?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json();document.querySelectorAll('.availability-value').forEach((node)=>{const balance=data[node.dataset.item];if(!balance)return;node.textContent=balance.available;const quantity=document.querySelector(`[name="quantities[${node.dataset.item}]"]`);quantity.max=balance.available;});message.textContent='Availability is calculated for the complete selected period and will be rechecked at submission and final approval.';}catch(e){message.textContent='Enter a valid period to calculate availability.';}},250);}
document.getElementById('needed_from').addEventListener('change',refreshAvailability);document.getElementById('return_due_at').addEventListener('change',refreshAvailability);refreshAvailability();
</script>
@endsection
