@extends('layouts.app', ['title' => $borrowingRequest->request_no])
@section('content')
@php($version=$borrowingRequest->currentVersion)
<section class="page-heading"><div><p class="eyebrow">Request {{ $borrowingRequest->request_no }} · Version {{ $version->version_no }}</p><h1>{{ $version->purpose_event }}</h1><p><span class="status {{ strtolower($borrowingRequest->status->value) }}">{{ $borrowingRequest->status->label() }}</span></p></div><div class="actions">@if($borrowingRequest->borrower_user_id===auth()->id() && in_array($borrowingRequest->status,[App\Enums\RequestStatus::Draft,App\Enums\RequestStatus::ReturnedForRevision],true))<a class="button secondary" href="{{ route('requests.edit',$borrowingRequest) }}">Edit draft</a>@endif</div></section>
<section class="content-grid two">
    <div class="card"><h2>Official request details</h2><dl class="detail-list"><dt>Accountable borrower</dt><dd>{{ $borrowingRequest->borrower->full_name }} ({{ $borrowingRequest->borrower->employee_no }})</dd><dt>Office/Department</dt><dd>{{ $borrowingRequest->accountableUnit->unit_name }}</dd><dt>Location</dt><dd>{{ $version->location }}</dd><dt>Needed from</dt><dd>{{ $version->needed_from->format('F j, Y g:i A') }}</dd><dt>Return deadline</dt><dd>{{ $version->return_due_at->format('F j, Y g:i A') }}</dd><dt>Event details</dt><dd>{{ $version->event_details }}</dd><dt>Represented activity</dt><dd>{{ $version->student_organization ?: 'Not applicable' }} · {{ $version->represented_program_department ?: 'Not applicable' }} {{ $version->represented_year_level }}</dd><dt>Off-campus</dt><dd>{{ $version->off_campus ? 'Yes - barricade only' : 'No' }}</dd></dl></div>
    <div class="card"><h2>Item lines</h2><div class="table-wrap"><table><thead><tr><th>Item</th><th>Requested</th><th>Approved</th></tr></thead><tbody>@foreach($version->items as $item)<tr><td>{{ $item->description_snapshot }}<small>{{ $item->unit_snapshot }}</small></td><td>{{ $item->requested_quantity+0 }}</td><td>{{ $item->approved_quantity!==null ? $item->approved_quantity+0 : 'Pending' }}</td></tr>@endforeach</tbody></table></div></div>
</section>
<section class="content-grid two">
    <div class="card"><h2>Approval chain</h2><div class="timeline">@foreach($version->approvalSteps->sortBy('sequence_no') as $step)<article><span>{{ $step->stage_code->value }}</span><div><strong>{{ str_replace('_',' ',$step->decision) }}</strong><p>{{ $step->approver?->full_name ?: 'Awaiting action officer' }}</p><small>Received: {{ optional($step->received_at)->format('M j, Y g:i A') ?: 'Pending' }} · Action: {{ optional($step->decided_at)->format('M j, Y g:i A') ?: 'Pending' }}</small>@if($step->remarks)<p>{{ $step->remarks }}</p>@endif</div></article>@endforeach</div></div>
    <div class="card"><h2>Controlled documents</h2><div class="document-list">@forelse($version->documents->sortByDesc('generated_at') as $document)<article><div><strong>{{ str_replace('_',' ',$document->document_type) }}</strong><small>{{ $document->document_no }} · {{ $document->status }} · {{ $document->generated_at->format('M j, Y g:i A') }}</small></div>@if(!in_array($document->status,['INVALIDATED','EXPIRED'],true))<a class="button secondary small" href="{{ route('documents.download',$document) }}">Download</a>@endif</article>@empty<p class="empty-state">Documents will appear as the request progresses.</p>@endforelse</div>
    @if($borrowingRequest->status===App\Enums\RequestStatus::FinalApprovedAwaitingDownload)<div class="callout warning"><strong>Download gate active</strong><p>Download the exact fully approved letter by {{ $borrowingRequest->download_deadline_at->format('F j, Y g:i A') }}. Only that download unlocks the Borrower's Slip.</p></div>@endif
    @if($borrowingRequest->custody)<a class="button primary" href="{{ route('custody.show',$borrowingRequest->custody) }}">Open Borrower's Slip and custody</a>@endif
    </div>
</section>
@if($borrowingRequest->borrower_user_id===auth()->id() && $borrowingRequest->status===App\Enums\RequestStatus::Draft)
<section class="content-area narrow"><form method="post" action="{{ route('requests.submit',$borrowingRequest) }}" class="card">@csrf<h2>Certify, e-sign, and submit</h2><p>I certify the request data and item quantities are accurate. The system will capture an immutable snapshot of my current profile e-signature.</p><button class="button primary">Sign and submit to SPMU</button></form></section>
@endif
@if(!in_array($borrowingRequest->status,[App\Enums\RequestStatus::Cancelled,App\Enums\RequestStatus::Rejected,App\Enums\RequestStatus::Expired],true) && !$borrowingRequest->custody?->released_at && ($borrowingRequest->borrower_user_id===auth()->id() || auth()->user()->hasRole('SPMU')))
<section class="content-area narrow"><form method="post" action="{{ route('requests.cancel',$borrowingRequest) }}" class="card danger-zone">@csrf<h2>Cancel request</h2><label>Mandatory reason<textarea name="reason" required></textarea></label><button class="button danger">Cancel and restore unreleased allocation</button></form></section>
@endif
<section class="content-area"><div class="card"><h2>Status history</h2><div class="timeline">@forelse($borrowingRequest->statusHistory as $history)<article><span>{{ $history->changed_at->format('M d') }}</span><div><strong>{{ str_replace('_',' ',$history->to_status) }}</strong><p>{{ $history->reason }}</p><small>{{ $history->actor?->full_name ?: 'System' }} · {{ $history->changed_at->format('M j, Y g:i A') }}</small></div></article>@empty<p>No transitions recorded yet.</p>@endforelse</div></div></section>
@endsection
